name: reactor_safety
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - openai
  - pymupdf
  - frontend
  - matplotlib
  - scikit-learn
  - wordcloud
  - spacy
post-build:
  - python -m spacy download en_core_web_sm